#!/bin/bash

if [ ! $# -eq 1 ] || [ ! -f $1 ]
then
	echo "Argumente insuficiente sau prea multe"
	echo "Utilizare: $0 fisier_text"
	exit 1
fi

F=$1
NR=`cat $F | grep -E -o "\<[1-9][0-9]*\>" | wc -l`
echo "Numarul de numere valide este: $NR"
NRS=`cat $F | grep -E -o "\<[1-9][0-9]*\>"`
S=0
for N in $NRS
do
	S=$(($S+$N))
done
echo "Suma numerelor valide este: $S"
