#!/bin/bash

if [ ! $# -eq 1 ]
then 
	echo "Trebuie sa introduceti ca argument un numar natural"
	exit 1
fi

N=$1

for i in `seq 1 $N` 
do
	touch file_$i.txt
	sed -n ''$i',+5p' /etc/passwd > file_$i.txt
done

