#!/bin/bash

if [ ! $# -eq 1 ]
then
	echo "Trebuie sa introduceti un director"
	exit 1
fi

D=$1	#directorul
CNT=0	#numarul total de fisiere text
SUM=0	#numarul total de linii

for F in `find $D -type f`
do	
	NR_l=0
	#verific daca e fisier text
	if file $F | grep -q "ASCII text$"
	then
		CNT=$(($CNT+1))
		NR_L=`wc -l $F | awk '{print $1}'`
	fi
	SUM=$(($SUM+$NR_L))
done
echo -n "Media este: "
echo `expr $SUM / $CNT`
