#!/bin/bash

if [ $# -eq 0 ]
then
	echo "Introduceti niste argumente"
	exit 1
fi

#iterez in argumente
for arg in $@
do
	if [ -f $arg ]
	then
		NRC=`cat $arg | wc -m`
		NRL=`cat $arg | wc -l`
		echo "Nume fisier: $arg ,caractere: $NRC, linii: $NRL"
	elif [ -d $arg ]
	then
		NRF=`find $arg -type f | wc -l`
		echo "Nume director: $arg, numar fisiere: $NRF"
	else
		echo "'$arg' nu e nici fisier nici director"
	fi
done
